# Generated by Django 6.1 on 2026-09-02 05:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
                ('no_of_slots', models.IntegerField(default=0)),
                ('city', models.CharField(default='India', max_length=30)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('available_slots', models.IntegerField(default=0)),
                ('opening_time', models.TimeField(default='08:00:00')),
                ('closing_time', models.TimeField(default='22:00:00')),
                ('security_level', models.CharField(choices=[('basic', 'Basic (Lighting)'), ('standard', 'Standard (CCTV)'), ('premium', 'Premium (24/7 Security)')], default='basic', max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parking_slots', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
