# Generated by Django 5.0.2 on 2025-03-02 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('provider', 'Provider'), ('finder', 'Finder'), ('admin', 'Admin')], default='admin', max_length=20),
        ),
    ]
