# Generated by Django 5.0.2 on 2025-04-01 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0003_parkingslot_userparkingbookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='mobile',
            field=models.CharField(blank=True, default='NULL', max_length=15, null=True),
        ),
    ]
