# Generated by Django 5.0.2 on 2025-04-01 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0004_customuser_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingslot',
            name='closing_time',
            field=models.TimeField(default='22:00:00'),
        ),
        migrations.AddField(
            model_name='parkingslot',
            name='opening_time',
            field=models.TimeField(default='08:00:00'),
        ),
        migrations.AddField(
            model_name='parkingslot',
            name='security_level',
            field=models.CharField(choices=[('basic', 'Basic (Lighting)'), ('standard', 'Standard (CCTV)'), ('premium', 'Premium (24/7 Security)')], default='basic', max_length=10),
        ),
    ]
