# Generated by Django 5.0.2 on 2025-04-06 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0006_reservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='end_time',
        ),
        migrations.AddField(
            model_name='parkingslot',
            name='city',
            field=models.CharField(default='India', max_length=30),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed')], default='pending', max_length=20),
        ),
    ]
